// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import { Script, console2 } from "forge-std/Script.sol";

/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IEfficientCallSmartWallet {
    function setOwner(address new_owner) external;

    function execute(address to, uint256 value, bytes calldata cd) external returns (bytes memory);

    function executeDelegatecall(address to, bytes calldata cd) external returns (bytes memory);

    function owner() external view returns (address);
}

contract ActionsScript is Script {
    function setOwner(address wallet, address who) public {
        vm.broadcast();
        IEfficientCallSmartWallet(wallet).setOwner(who);
    }

    function execute(address wallet, address to, uint256 value, bytes memory cd) public {
        vm.broadcast();
        IEfficientCallSmartWallet(wallet).execute(to, value, cd);
    }

    function executeDelegatecall(address wallet, address to, bytes memory cd) public {
        vm.broadcast();
        IEfficientCallSmartWallet(wallet).executeDelegatecall(to, cd);
    }
}
